name: zmeulkit
description: Zmeul Kit OTP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  awesome_select: ^6.0.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  #flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.18
  google_fonts: ^4.0.3
  introduction_screen: ^3.1.6
  photo_view: ^0.14.0
  image: ^4.0.15
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  pin_code_fields: ^7.3.0
  image_picker: ^0.8.6+2
  flutter_custom_clippers: ^2.1.0
  animated_splash_screen: ^1.3.0
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  avatar_view: ^1.0.1
  fluttericon: ^2.0.0
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tkyo.png"

